version: '3.8'
services:
  app:
    build: .
    container_name: currency-rate-app
    restart: unless-stopped
    environment:
      PORT: 8000
      ENVIRONMENT: Local
      RATES_UPDATE_CRON_IN_SECONDS: 10
      RATES_UPDATE_BATCH_SIZE: 10
      HTTP_CLIENTS_DEFAULT_TIMEOUT_IN_SECONDS: 15
      DATABASE_HOST: postgres
      DATABASE_USERNAME: admin
      DATABASE_PASSWORD: admin
      DATABASE_PORT: 5432
      DATABASE_NAME: test
      FRANKFURTER_API_URL: https://api.frankfurter.dev
      RATES_API_TYPE: Frankfurter
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test
      PGDATA: /var/lib/postgresql/data/pgdata
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - '8888:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
volumes:
  postgres_data:
